[Seat:*]
display-setup-script=/usr/local/sbin/retail-display-setup
autologin-user=arduino
autologin-user-timeout=0
autologin-session=retail-queue-kiosk
user-session=retail-queue-kiosk
allow-guest=false
